#!/bin/bash

if [ "$1" = "clean" ]
then

    ./_dist/site clean
    rm -r _dist

elif [ "$1" = "site" ]
then

    ./_dist/site build

elif [ "$1" = "deploy" ]
then

    ./_dist/site deploy

elif [ "$1" = "preview" ]
then

    ./_dist/site watch
    # -p 9000

else

    mkdir -p _dist
    ghc -odir _dist -hidir _dist -O2 --make site.hs -o _dist/site
    ./_dist/site rebuild

fi

rm -f rubtmp*.{pdf,tex,log,aux,out} missfont.log
